name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Checkout your repository

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Setup Node.js environment
        with:
          node-version: '20' # Set to Node.js v20

      - name: Install dependencies
        run: npm install # Install all dependencies

      - name: Build project
        run: npm run build # Build the project using your build script

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4 # Upload build files for deployment
        with:
          name: production-files
          path: ./dist # The output directory

  deploy:
    name: Deploy
    needs: build # Ensure deployment happens after build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy from the main branch

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 # Download the build artifact
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Deploy to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token to authorize deployment
          publish_dir: ./dist # Directory with production-ready files
