name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when changes are pushed to the main branch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3 # Checkout the repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Use the latest LTS version of Node.js

      - name: Install dependencies
        run: npm install # Install npm dependencies

      - name: Build project
        run: npm run build # Build the project

  deploy:
    name: Deploy
    needs: build # Ensure the build job runs before deploying
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Authentication token for GitHub Pages
          publish_dir: ./dist # Directory to deploy from (match Vite build output)
